version: 2.1

# Define a job to be invoked later in a workflow.

orbs:
  test-harness: dborowiecki/testutils@0.1.5

workflows:
  test_everything:
    jobs:
      - test-harness/create-config
      - test-harness/execute-tests
