version: 2.1
setup: true


orbs:
  test-harness: dborowiecki/testutils@0.2.4

workflows:
  test_everything:
    jobs:
      - test-harness/create-config:
          post-steps: # Persist to workspace has to be defined in main workflow 
            - persist_to_workspace:
                root: workspace
                paths:
                  - generated.yml
      - test-harness/execute-tests:
          requires:
          - test-harness/create-config
