version: 2.1
setup: true

orbs:
  testutils: dborowiecki/testutils@0.2.7

workflows:
  test_everything:
    jobs:
      - testutils/create-config:
          post-steps: # Persist to workspace has to be defined in main workflow
            - persist_to_workspace:
                root: workspace
                paths:
                  - generated.yml
      - testutils/execute-tests:
          requires:
            - testutils/create-config 
