before: 
  steps:
    - run:
        name: Send POST Request to FastAPI Endpoint
        command: |
          curl -X POST $API_URL/test -H "Content-Type: application/json" -d "{\"secret\":\"$SECRET_VAR\"}"

after: 
  steps:
  - run:
      name: Print Hello World 2
      command: echo "Hello World 2"
